using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using EnumComposer;
using System.ComponentModel;

namespace UtComposer
{

    #region AutoGenerated

    //SQLSelect:f__id, f_name, T_XXX
    public enum E1
    {
        Op1 = 23,
        Op2 = 23,
    }

    class SomeClass
    {
        class SomeOther
        {
            [EnumSqlCnn("server1", "database2")]
            [EnumSqlSelect("SELECT lkc__id, lkc_name FROM AcClaim.dbo.T_LookupCategories")]
            public enum E2
            {
                [Description("ss")]
                K2 = 344,
                //[DescriptionAttribute("K4")]
                //K4 = 455,
                K5 = 534,
            }
        }
    }

    public enum E3
    {
        a3,
        //A0
        A4,
        A5 = 455,
    }

    public class TestEnumerations
    {

    }

    #endregion AutoGenerated

}
