using EnumComposer;/*
..*/
namespace FakeDellExpected
{

    [EnumSqlCnn("#SQL", "Server=(local);Database=AdventureWorks2014;User=ArcticsReader;Password=ArcticsReaderPass;")]
    [EnumSqlSelect("SELECT ContactTypeID, Name FROM Person.ContactType")]
    public enum ContactTypeEnum
    {
        PreHearing = 7,
        //Hearing = 8,
        SD = 5,
    }/*one*//*



    #endregion AutoGenerated
    *///two    
    [EnumSqlSelect("SELECT AddressTypeId, Name FROM Person.AddressType")]
    public enum AddressTypeEnum
    {
    }/*one*//*

    */
}/*and here*/