using EnumComposer;/*
..*/
namespace FakeDellExpected
{

    [EnumSqlCnn("(local)", "AdventureWorks2014")]
    [EnumSqlSelect("SELECT ContactTypeID, Name FROM Person.ContactType")]
    public enum ContactTypeEnum
    {
        ExportAdministrator = 5,
        //InternationalMarketingManager = 6,
        MarketingAssistant = 7,
    }/*one*//*



    #endregion AutoGenerated
    *///two    
    [EnumSqlSelect("SELECT AddressTypeId, Name FROM Person.AddressType")]    
    public enum AddressTypeEnum
    {
    }/*one*//*

    */
}/*and here*/