using EnumComposer;/*
..*/
namespace FakeDellExpected
{

    [EnumSqlCnn("(local)", "AdventureWorks2014")]
    [EnumSqlSelect("SELECT ContactTypeID, Name FROM Person.ContactType")]
    public enum ContactTypeEnum
    {
        //AccountingManager = 1,
        //AssistantSalesAgent = 2,
        //AssistantSalesRepresentative = 3,
        //CoordinatorForeignMarkets = 4,
        ExportAdministrator = 5,
        //InternationalMarketingManager = 6,
        MarketingAssistant = 7,
        //MarketingManager = 8,
        //MarketingRepresentative = 9,
        //OrderAdministrator = 10,
        //Owner = 11,
        //Owner_MarketingAssistant = 12,
        //ProductManager = 13,
        //PurchasingAgent = 14,
        //PurchasingManager = 15,
        //RegionalAccountRepresentative = 16,
        //SalesAgent = 17,
        //SalesAssociate = 18,
        //SalesManager = 19,
        //SalesRepresentative = 20,
    }/*one*//*



    #endregion AutoGenerated
    *///two    
    [EnumSqlSelect("SELECT AddressTypeId, Name FROM Person.AddressType")]
    public enum AddressTypeEnum
    {
        //Billing = 1,
        //Home = 2,
        //MainOffice = 3,
        //Primary = 4,
        //Shipping = 5,
        //Archive = 6,
    }/*one*//*

    */
}/*and here*/