using EnumComposer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UtComposer
{
    //#region AutoGenerated
    //a
    [EnumSqlCnn("", "")]
    [EnumSqlSelect("SELECT lkc__id, lkc_name FROM T_AwayType")]
    public enum AwayTypeEnum
    {
        //MediationFaceToFace = 2,
        //MediationPhone = 3,
        //Administrative = 4,
        //Vacation = 5,
        //WritingDay = 6,
        //Training = 22,
        //Seminar = 23,
        //NotAvailable = 24,
        //SickDays = 39,
        //OldHoliday = 41,
        //Holiday = 42,
        //ExternalEvent = 43,
        //ReligiousHoliday = 46,
    }
    //b
    class X
    {
        class Y
        {
            [EnumSqlSelect("SELECT lkc__id, lkc_name FROM T_MeetingType")]
            public enum MeetingTypeEnum
                {
                    SD = 5,
                    PreHearing = 7,
                    Hearing = 8,
                }//c
        }
    }

     //c2
    [EnumSqlSelect("SELECT lkc__id, lkc_name FROM T_AwaySystem")]
    public enum AwaySystemTypeEnum
    {
        Default = 98000,
        Mediation = 98001,
        Arbitration = 98002,
        Appeals = 98003,
    }//end
     //and    
     /*    */
    [EnumSqlSelect("SELECT lkc__id, lkc_name FROM T_Location")]
    public enum LocationEnum
    {
        ToBeScheduledArb = 100,
        WrittenSubmissions = 129,
    }/**/

    //#endregion AutoGenerated
}/*one*/