using EnumComposer;/*
..*/
namespace FakeDellExpected
{

    [EnumSqlCnn("DELLSTUDIOXPS", "Arctics")]
    [EnumSqlSelect("SELECT mt__id, mt_name FROM T_MeetingTypes")]
    public enum MeetingTypeEnum
    {
        PreHearing = 7,
        //Hearing = 8,
        SD = 5,
    }/*one*//*



    #endregion AutoGenerated
    *///two    
    [EnumSqlSelect("SELECT mt__id, mt_name FROM T_MeetingTypes")]
    public enum MeetingTypeEnum2
    {
    }/*one*//*

    */
}/*and here*/