using EnumComposer;/*
..*/
namespace FakeDellExpected
{
  

    [EnumSqlSelect("SELECT mt__id, mt_name FROM T_MeetingTypes")]
    public enum MeetingTypeEnum
    {
        PreHearing = 7,
        //Hearing = 8,
        SD = 5,
    }/*one*//*

    #endregion AutoGenerated
    *///two
}/*and here*/